// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaiennljjjvstovtpdhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhaWVubmxqamp2c3RvdnRwZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODc2MzAsImV4cCI6MjA2ODc2MzYzMH0.B20wIMuHA8CX1dksawMWm_CTmAy2f2gg_oeD8xw_ObM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});